from odoo import models, fields, api
import logging

_logger = logging.getLogger(__name__)

class CrmLead(models.Model):
    _inherit = 'crm.lead'

    ai_lead_score = fields.Integer(string='AI Score', readonly=True, help="Score generated by AI Agent (0-100)")
    ai_summary = fields.Text(string='AI Analysis', readonly=True)
    ai_generated_email = fields.Html(string='Draft AI Email')

    def action_trigger_ai_evaluation(self):
        """Manual trigger for a single lead, callable from a button"""
        for lead in self:
            if not lead.email_from and not lead.contact_name:
                continue

            _logger.info("Triggering AI Agent for Lead: %s", lead.name)

            # Simulated AI Call (Replace with real OpenAI/Anthropic API call)
            # You would construct a prompt using lead.name, lead.description, etc.

            # Dummy logic for demonstration
            name_len = len(lead.name) if lead.name else 5
            score = name_len * 5
            summary = f"Based on the initial analysis of {lead.name}, this lead shows potential. A personalized outreach is recommended."
            email = f"<p>Hi {lead.contact_name or 'there'},</p><p>I noticed your interest in our services. Could we schedule a brief call next week to discuss how we can help {lead.partner_name or 'your company'}?</p>"

            lead.write({
                'ai_lead_score': min(score, 100),
                'ai_summary': summary,
                'ai_generated_email': email
            })

            lead.message_post(body=f"AI Agent Evaluation Complete. Assigned Score: {min(score, 100)}")

    @api.model
    def _cron_evaluate_new_leads(self):
        """Cron job method to process batches of new leads"""
        leads_to_process = self.search([
            ('ai_lead_score', '=', 0),
            ('type', '=', 'lead'),
            ('active', '=', True)
        ], limit=50)

        for lead in leads_to_process:
            try:
                lead.action_trigger_ai_evaluation()
                self.env.cr.commit() # Commit after each lead to prevent one failure from rolling back the batch
            except Exception as e:
                _logger.error("Failed to evaluate lead %s: %s", lead.id, str(e))
                self.env.cr.rollback()
